=== MariaBonnin/Entornos/src/main/java/pedido.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT pedido (codigo.pedido, nombre.trabajador, fecha.pedido, observaciones.pedido?,
 plazo.revision, articulos.pedidos)>
<!ELEMENT articulos.pedidos (articulo+)>
<!ELEMENT articulo (codigo.articulo, cantidad, precio, observaciones.articulo)>

<!ELEMENT codigo.pedido (#PCDATA)>
<!ELEMENT nombre.trabajador (#PCDATA)>
<!ELEMENT fecha.pedido (#PCDATA)>
<!ELEMENT observaciones.pedido (#PCDATA)>
<!ELEMENT plazo.revision (#PCDATA)>
<!--A "articulos.pedidos" y "articulo" no le he asignado (#PCDATA) porque no 
contienen nada en su interior, excepto otras etiquetas ¿sería correcto?-->
<!ELEMENT codigo.articulo (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT observaciones.articulo (#PCDATA)>

<!ATTLIST observaciones.pedido valor CDATA #REQUIRED>
<!ATTLIST plazo.revision plazoFinal CDATA #REQUIRED>

=== MariaBonnin/Entornos/DistanzaSA.xml
<?xml version = "1.0" encoding = "utf-8"?>
<!DOCTYPE pedido SYSTEM "pedido.dtd">
<pedido>
    <codigo.pedido>formado por unha cadea de 8 caracteres dos cales o primeiro é unha letra.</codigo.pedido>
    <nombre.trabajador>quien realiza el pedido</nombre.trabajador>
    <fecha.pedido>fecha</fecha.pedido>
    <observaciones.pedido valor="urgente">Observacións sobre o pedido, cuxos valores son, en caso de que exista o dato: urxente ou incompleto.</observaciones.pedido>
    <plazo.revision plazoFinal="25/10/2021"> X días.   ?????Prazo de revisión dos produtos recibidos que será un intervalo de tempo expresado en días e dependerá do prezo final do pedido.</plazo.revision>
    <articulos.pedidos>
    <articulo>
        <codigo.articulo>formado por tres letras maiúsculas e tres díxitos separados por un guión</codigo.articulo>
        <cantidad> Número de unidades pedidas.</cantidad>
        <precio> Prezo de cada unidade.</precio>
        <observaciones.articulo>observaciones</observaciones.articulo>
    </articulo>
    
    </articulos.pedidos>

</pedido>

=== MariaBonnin/Entornos/src/main/java/DistanzaSL.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedido SYSTEM "pedido.dtd">
<pedido xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
           xsi:SchemaLocation= "newXmlSchema.xsd">
    <codigo.pedido> A2587469 </codigo.pedido>
    <nombre.trabajador>Pablo Pérez</nombre.trabajador>
    <fecha.pedido>04/10/21</fecha.pedido>
    <observaciones.pedido valor="urgente">Observacións sobre o pedido.</observaciones.pedido>

    <plazo.revision plazoFinal="11/03/2021"> 30 días </plazo.revision>
    <articulos.pedidos>
        <articulo>
            <codigo.articulo>LKM-241</codigo.articulo>
            <cantidad> 25</cantidad>
            <precio> Prezo de cada unidade.</precio>
            <observaciones.articulo>observaciones</observaciones.articulo>

        </articulo>

    </articulos.pedidos>

</pedido>
