=== MariaBonnin/Entornos/src/main/java/pintura.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT pinturas (pintura+)>
<!-- puede haber tecnicas mixtas-->
<!ELEMENT pintura (nombrePintor, tituloObra, tecnica+, superficie,buenEstadoConservacion, nombrePrestado)>
<!ELEMENT nombrePintor (#PCDATA)>
<!ELEMENT tituloObra (#PCDATA)>
<!ELEMENT tecnica (#PCDATA)>
<!ELEMENT superficie (#PCDATA)>
<!ELEMENT buenEstadoConservacion (#PCDATA)>
<!ELEMENT nombrePrestado (#PCDATA)>
<!ATTLIST tituloObra codigoObra ID #REQUIRED>
<!ATTLIST tituloObra fechaRealizacion NMTOKENS #REQUIRED>
<!ATTLIST nombrePrestado fechaPrestamo NMTOKENS #REQUIRED>

=== MariaBonnin/Entornos/src/main/java/pintura.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pinturas SYSTEM "pintura.dtd">
<pinturas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:SchemaLocation= "pintura.xsd">
<pintura>
	<nombrePintor>Julio Méndez</nombrePintor>
	<tituloObra codigoObra="4523657"
		fechaRealizacion="2004-10-25">Tres gatos en un tejado</tituloObra>
	<tecnica>carboncillo</tecnica>
	<superficie>lienzo</superficie>
	<buenEstadoConservacion>si</buenEstadoConservacion>
	<nombrePrestado fechaPrestamo="2012-09-24">Alicia Gómez</nombrePrestado>
</pintura>
</pinturas>
